# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d49fc1ed0fa01b6d157e7a2eceb143ede8cc6d5d079484a89272abcb7d746a28a9c30381a5b4b9dbb23b35ddf8b4489c75b25291b91ae3536a2b51a450efae0

test:
  secret_key_base: 0f8809bd88c1f86c346a273f1062b94fa6a97433c555b25b8015fa8a3dcb10b4c89081b5f82b499c2423f9abf75a8f5e8566fe5402d75bce36c75c9d604b73e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
